application: blobstorebug
version: 1
runtime: go
api_version: go1

handlers:

  - url: /
    static_files: index.html
    upload: index.html

  - url: /uploadURL
    script: _go_app

  - url: /upload
    script: _go_app
